### ISSUE TITLE
[v2.1.0] "Socket error: timeout" on Linux with Proton

### ISSUE THREAD

**Issue by AnErrupTion** [BeamMP/BeamMP-Launcher#62]
Hello!

I'm having an issue (even with the latest stable version of the launcher) where I can see the Multiplayer menu in the game,  but clicking on it I get "The game is not connected to the launcher! Please start the game using the BeamMP Launcher.", and in the console, I get:

```
35.87080|E|GELua.MPCoreNetwork.send| Socket error: timeout
35.87096|E|GELua.MPCoreNetwork.send| Stopped at index: 0 while trying to send 1 bytes of data.
```

I'm using Void Linux with Proton GE 8.11, but I also tried with Proton Experimental, with no success (same error).

**Comment by Anonymous-275** [comment]
this seems to be the wrong lua version since 2.1 does not use sockets anymore

**Comment by AnErrupTion** [comment]
> this seems to be the wrong lua version since 2.1 does not use sockets anymore

So what can I do? I'm simply running the executable, I'm not trying to modify anything related to Lua.

**Comment by Anonymous-275** [comment]
> > this seems to be the wrong lua version since 2.1 does not use sockets anymore
> 
> So what can I do? I'm simply running the executable, I'm not trying to modify anything related to Lua.

we just pushed the lua update, running it again should download the correct lua and get your right in!

**Comment by AnErrupTion** [comment]
@Anonymous-275 It worked!!!! However, just a side note: the launcher tried to put the mod in ``AppData\Local\BeamNG.drive\mods\multiplayer``, even though it should be in ``AppData\Local\BeamNG.drive\0.29\mods\multiplayer``, otherwise the mod isn't recognized in BeamNG.drive.

**Comment by AnErrupTion** [comment]
@Anonymous-275 Hello again! With 0.30.5 and launcher v2.1.1, I'm getting the exact same error again. Is it the fact that you forgot to push an update again, or is it another incompatibility issue?

**Comment by Anonymous-275** [comment]
this update does indeed require a lua update aswell
